### ISSUE TITLE
Problem from update 0.4.0 to the 0.4.5

### ISSUE THREAD

**Issue by tuvok81** [Razzmatazzz/ValheimServerWarden#17]
Hey,
1. when i update the Tool than i get this window..
![grafik](https://user-images.githubusercontent.com/30367063/109707788-de519280-7b9a-11eb-8c21-eb01cd5d58bd.png)

2. i go to "manual"
3.  when i go to "Default Server Path" the Tool will closed without errors.
![grafik](https://user-images.githubusercontent.com/30367063/109707863-fa553400-7b9a-11eb-96b1-ee3367e84202.png)

3b. the Windows Protokoll

Application: Valheim Server Warden.exe
CoreCLR Version: 5.0.321.7212
.NET Version: 5.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at ValheimServerWarden.MainWindow.btnServerPath_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ValheimServerWarden.App.Main()

4. and why lost the tool the Path? i have add this to the older versions?

**Comment by SkOODaT** [comment]
im seeing the same issues ... cannot browse for directories now it crashes
not sure if 1 of the bugfixes included the player list either i saw alot of strangeness with it after vsw-0.4.1.0 was the last really good working version for me

**Comment by Razzmatazzz** [comment]
That crash should be fixed in the latest version.

@SkOODaT Can you be more specific about the "strangeness" you've experienced with the player list? It's exceedingly difficult to troubleshoot something that vague.

**Comment by SkOODaT** [comment]
> @SkOODaT Can you be more specific about the "strangeness" you've experienced with the player list? It's exceedingly difficult to troubleshoot something that vague.

i was seeing players get doubled or when one disconnected, or players weren't listed etc, just incorrect list, started after vsw-0.4.1.0 ill try your newest ver tho see if  the bug fixes , fixed it

**Comment by Razzmatazzz** [comment]
Please turn on the raw server logging option and then provide that log for a session when you see any of those kinds of issues.

**Comment by SkOODaT** [comment]
i have the logging on already as i use a node html page to show status too, since it reads from the same place thats how i noticed lol, im running your latest now it seems to be ok ... ill keep my eyes open tho and if it happens again ill grab ya a log
